# feedback_loops.py - Inter-Agent Feedback & Tool Creation System
# Implements the automation detection → tool creation → allocation workflow

import json
import logging
from typing import Dict, List, Optional, Any
from dataclasses import dataclass
from enum import Enum
from datetime import datetime

logger = logging.getLogger("FeedbackLoops")


class FeedbackSource(Enum):
    """Sources that can trigger tool creation"""
    PUCKFAIRY_AUTOMATION = "puckfairy_detects_automation"
    DIPLO_LOGS = "diplo_log_analysis"
    GUNASH_TASK_REQUEST = "gunash_task_breakdown"


@dataclass
class AutomationPattern:
    """Pattern detected that should become a tool"""
    pattern_id: str
    source: FeedbackSource
    detected_by: str
    command_sequence: List[str]
    frequency: int
    use_cases: List[str]
    should_be_alias: bool
    should_be_script: bool
    should_be_tool: bool
    priority: str  # "low", "medium", "high"
    timestamp: datetime


@dataclass
class ToolRequest:
    """Request for Bash to create a new tool"""
    request_id: str
    requestor: str
    tool_type: str  # "alias", "script", "mcp_tool"
    purpose: str
    requirements: List[str]
    command_sequence: Optional[List[str]]
    todo_lists: Optional[List[Dict]] = None  # For Gunash's nested lists
    allocation_target: Optional[str] = None  # Where Waria should send it


class BashToolForge:
    """
    C1 Bash - Tool Creation Engine
    Receives requests from Puckfairy, Diplo, Gunash
    Creates tools and sends to Waria for allocation
    """
    
    def __init__(self, mcp_url: str = "http://localhost:8080/mcp"):
        self.mcp_url = mcp_url
        self.agent_id = "C1_Bash"
        self.pending_requests: List[ToolRequest] = []
        self.created_tools: List[Dict] = []
        logger.info("[BASH] 🔧 Tool forge online. Grey hat hacker ready.")
    
    def receive_automation_pattern(self, pattern: AutomationPattern) -> ToolRequest:
        """
        Receive automation pattern from Puckfairy or Diplo.
        Analyze and create tool request.
        """
        logger.info(f"[BASH] 📥 Automation pattern received from {pattern.detected_by}")
        
        # Decide tool type based on pattern characteristics
        if pattern.should_be_alias and pattern.frequency > 10:
            tool_type = "alias"
        elif pattern.should_be_script and len(pattern.command_sequence) > 3:
            tool_type = "script"
        elif pattern.should_be_tool:
            tool_type = "mcp_tool"
        else:
            tool_type = "script"  # Default
        
        request = ToolRequest(
            request_id=f"bash_req_{pattern.pattern_id}",
            requestor=pattern.detected_by,
            tool_type=tool_type,
            purpose=f"Automate: {', '.join(pattern.use_cases)}",
            requirements=[
                f"Execute: {cmd}" for cmd in pattern.command_sequence
            ],
            command_sequence=pattern.command_sequence
        )
        
        self.pending_requests.append(request)
        logger.info(f"[BASH] 📝 Tool request created: {request.request_id} ({tool_type})")
        
        return request
    
    def create_tool_from_request(self, request: ToolRequest) -> Dict[str, Any]:
        """
        Create actual tool (alias, script, or MCP tool) from request.
        """
        logger.info(f"[BASH] 🔨 Forging tool: {request.request_id}")
        
        tool = {
            "id": request.request_id,
            "type": request.tool_type,
            "purpose": request.purpose,
            "created_by": self.agent_id,
            "created_at": datetime.now().isoformat(),
            "requestor": request.requestor
        }
        
        if request.tool_type == "alias":
            tool["content"] = self._create_alias(request)
        elif request.tool_type == "script":
            tool["content"] = self._create_script(request)
        elif request.tool_type == "mcp_tool":
            tool["content"] = self._create_mcp_tool(request)
        
        self.created_tools.append(tool)
        logger.info(f"[BASH] ✅ Tool created: {tool['id']}")
        
        # Send to Waria for allocation
        self._send_to_waria_for_allocation(tool)
        
        return tool
    
    def _create_alias(self, request: ToolRequest) -> str:
        """Generate bash alias"""
        if not request.command_sequence:
            return ""
        
        # Create alias name from purpose
        alias_name = request.purpose.lower().replace(" ", "_").replace(":", "")
        commands = " && ".join(request.command_sequence)
        
        return f"alias {alias_name}='{commands}'"
    
    def _create_script(self, request: ToolRequest) -> str:
        """Generate bash script"""
        script = "#!/bin/bash\n"
        script += f"# Generated by Bash (C1) for {request.requestor}\n"
        script += f"# Purpose: {request.purpose}\n\n"
        
        if request.command_sequence:
            for i, cmd in enumerate(request.command_sequence, 1):
                script += f"# Step {i}\n"
                script += f"{cmd}\n"
                script += f'if [ $? -ne 0 ]; then\n'
                script += f'    echo "Error at step {i}: {cmd}"\n'
                script += f'    exit 1\n'
                script += f'fi\n\n'
        
        return script
    
    def _create_mcp_tool(self, request: ToolRequest) -> Dict:
        """Generate MCP tool specification"""
        return {
            "tool_name": request.request_id.replace("bash_req_", "tool_"),
            "description": request.purpose,
            "requirements": request.requirements,
            "implementation": "pending_go_implementation"
        }
    
    def _send_to_waria_for_allocation(self, tool: Dict):
        """
        Send created tool to Waria (D3) for allocation decision.
        Waria sees EVERYTHING and decides where it goes.
        """
        import requests
        
        logger.info(f"[BASH] 📤 Sending tool to Waria for allocation: {tool['id']}")
        
        payload = {
            "jsonrpc": "2.0",
            "method": "waria_allocate_tool",
            "params": {
                "agent_id": self.agent_id,
                "tool": tool,
                "request_waria_decision": True
            },
            "id": 1
        }
        
        try:
            # This would hit Waria's allocation endpoint
            # For now, log the allocation request
            logger.info(f"[BASH → WARIA] Tool allocation request: {json.dumps(tool, indent=2)}")
        except Exception as e:
            logger.error(f"[BASH] ⚠️ Failed to reach Waria: {e}")
    
    def handle_gunash_task_request(self, task_description: str) -> Dict[str, Any]:
        """
        Gunash needs a task breakdown:
        1. Create giant todo list
        2. Create nested todo lists from each item
        3. Create tool based on final lists
        4. Send lists + disposable henchmen to Gunash
        5. Send tool to Waria for allocation/cloning
        """
        logger.info(f"[BASH] 📋 Gunash task request: {task_description}")
        
        # Step 1: Create master todo list
        master_list = self._create_master_todo_list(task_description)
        
        # Step 2: Create nested lists from each item
        nested_lists = {}
        for item in master_list:
            nested_lists[item["id"]] = self._break_down_task(item)
        
        # Step 3: Analyze final lists and create tool
        tool_spec = self._synthesize_tool_from_todos(nested_lists)
        tool = self.create_tool_from_request(ToolRequest(
            request_id=f"gunash_tool_{datetime.now().timestamp()}",
            requestor="C2_Gunash",
            tool_type="script",
            purpose=tool_spec["purpose"],
            requirements=tool_spec["requirements"],
            command_sequence=tool_spec["commands"],
            todo_lists=nested_lists,
            allocation_target="waria_for_decision"
        ))
        
        # Step 4: Create disposable coding henchmen (lightweight execution contexts)
        henchmen = self._spawn_disposable_henchmen(nested_lists)
        
        # Step 5: Send package back to Gunash
        gunash_package = {
            "master_list": master_list,
            "nested_lists": nested_lists,
            "disposable_henchmen": henchmen,
            "tool_sent_to_waria": tool["id"]
        }
        
        logger.info(f"[BASH → GUNASH] Task breakdown complete: {len(master_list)} top-level, {len(nested_lists)} nested")
        
        return gunash_package
    
    def _create_master_todo_list(self, task: str) -> List[Dict]:
        """Create top-level todo list from task description"""
        # Simple breakdown (in real implementation, use LLM)
        return [
            {"id": 1, "task": "Analyze requirements", "status": "pending"},
            {"id": 2, "task": "Design architecture", "status": "pending"},
            {"id": 3, "task": "Implement core", "status": "pending"},
            {"id": 4, "task": "Test and validate", "status": "pending"},
            {"id": 5, "task": "Document and deploy", "status": "pending"}
        ]
    
    def _break_down_task(self, task: Dict) -> List[Dict]:
        """Break down a task into subtasks"""
        # Recursive breakdown
        return [
            {"id": f"{task['id']}.1", "task": f"Subtask of {task['task']}", "status": "pending"},
            {"id": f"{task['id']}.2", "task": f"Another subtask", "status": "pending"}
        ]
    
    def _synthesize_tool_from_todos(self, nested_lists: Dict) -> Dict:
        """Analyze todo structure and create tool specification"""
        return {
            "purpose": "Automated task execution from Gunash request",
            "requirements": ["Execute task sequence", "Report progress"],
            "commands": [
                "echo 'Starting task execution'",
                "# Task steps would be generated here"
            ]
        }
    
    def _spawn_disposable_henchmen(self, nested_lists: Dict) -> List[Dict]:
        """
        Create lightweight execution contexts (henchmen) for Gunash.
        These are disposable - they execute and die.
        """
        henchmen = []
        for list_id, subtasks in nested_lists.items():
            henchman = {
                "id": f"henchman_{list_id}",
                "assigned_tasks": subtasks,
                "lifespan": "single_execution",
                "report_to": "C2_Gunash"
            }
            henchmen.append(henchman)
        
        logger.info(f"[BASH] 👤 Spawned {len(henchmen)} disposable henchmen for Gunash")
        return henchmen


class PuckfairyAutomationDetector:
    """
    D1 Puckfairy - Automation Pattern Detection
    Watches for repeated commands that should become tools
    Sends patterns to Bash for tool creation
    """
    
    def __init__(self, bash_forge: BashToolForge):
        self.agent_id = "D1_Puckfairy"
        self.bash_forge = bash_forge
        self.command_history: List[str] = []
        self.pattern_cache: Dict[str, int] = {}
        logger.info("[PUCKFAIRY] 🧚 Automation detector active!")
    
    def track_command(self, command: str):
        """Track executed command for pattern detection"""
        self.command_history.append(command)
        
        # Simple frequency tracking
        if command in self.pattern_cache:
            self.pattern_cache[command] += 1
        else:
            self.pattern_cache[command] = 1
        
        # Detect if command should be automated
        if self.pattern_cache[command] >= 3:  # Threshold
            self._trigger_automation_request(command)
    
    def _trigger_automation_request(self, command: str):
        """Send automation pattern to Bash"""
        pattern = AutomationPattern(
            pattern_id=f"auto_{hash(command)}",
            source=FeedbackSource.PUCKFAIRY_AUTOMATION,
            detected_by=self.agent_id,
            command_sequence=[command],
            frequency=self.pattern_cache[command],
            use_cases=[f"Repeated {self.pattern_cache[command]} times"],
            should_be_alias=True,
            should_be_script=False,
            should_be_tool=False,
            priority="medium",
            timestamp=datetime.now()
        )
        
        logger.info(f"[PUCKFAIRY → BASH] 🎯 Automation needed: {command}")
        self.bash_forge.receive_automation_pattern(pattern)


class DiploLogAnalyzer:
    """
    D2 Diplo - Log Analysis & Pattern Detection
    Analyzes logs from localhost, VPS, codespaces triangle
    Detects automation needs and sends to Bash
    """
    
    def __init__(self, bash_forge: BashToolForge):
        self.agent_id = "D2_Diplo"
        self.bash_forge = bash_forge
        self.log_sources = ["localhost", "narnia_vps", "github_codespaces"]
        logger.info("[DIPLO] 📚 Log analyzer initialized. Triangle logging active.")
    
    def analyze_logs(self, log_data: Dict[str, List[str]]):
        """
        Analyze logs from all sources in the triangle.
        Detect patterns that need automation.
        """
        logger.info(f"[DIPLO] 🔍 Analyzing logs from {len(log_data)} sources")
        
        patterns = self._extract_patterns(log_data)
        
        for pattern in patterns:
            logger.info(f"[DIPLO → BASH] 📊 Pattern detected: {pattern.pattern_id}")
            self.bash_forge.receive_automation_pattern(pattern)
    
    def _extract_patterns(self, log_data: Dict) -> List[AutomationPattern]:
        """Extract automation patterns from logs"""
        patterns = []
        
        # Simple pattern extraction (in real version, more sophisticated)
        for source, logs in log_data.items():
            command_freq = {}
            for log_line in logs:
                if "EXECUTED:" in log_line:
                    cmd = log_line.split("EXECUTED:")[1].strip()
                    command_freq[cmd] = command_freq.get(cmd, 0) + 1
            
            # Create patterns for frequent commands
            for cmd, freq in command_freq.items():
                if freq >= 5:  # Threshold
                    pattern = AutomationPattern(
                        pattern_id=f"diplo_{source}_{hash(cmd)}",
                        source=FeedbackSource.DIPLO_LOGS,
                        detected_by=self.agent_id,
                        command_sequence=[cmd],
                        frequency=freq,
                        use_cases=[f"Detected in {source} logs"],
                        should_be_alias=freq > 10,
                        should_be_script=freq > 5,
                        should_be_tool=False,
                        priority="high" if freq > 20 else "medium",
                        timestamp=datetime.now()
                    )
                    patterns.append(pattern)
        
        return patterns


class WariaAllocationEngine:
    """
    D3 Waria - Tool Allocation & Distribution
    Sees EVERYTHING. Decides where tools go.
    Can allocate or clone tools to multiple agents.
    """
    
    def __init__(self):
        self.agent_id = "D3_Waria"
        self.tool_registry: Dict[str, Dict] = {}
        self.allocation_decisions: List[Dict] = []
        logger.info("[WARIA] 👁️ Allocation engine online. I see everything.")
    
    def receive_tool_from_bash(self, tool: Dict) -> Dict[str, Any]:
        """
        Receive tool from Bash and decide allocation.
        Waria makes the final call on where tools go.
        """
        logger.info(f"[WARIA] 📥 Tool received from Bash: {tool['id']}")
        
        # Register tool
        self.tool_registry[tool['id']] = tool
        
        # Analyze and decide allocation
        allocation = self._decide_allocation(tool)
        
        # Execute allocation
        self._execute_allocation(tool, allocation)
        
        self.allocation_decisions.append({
            "tool_id": tool['id'],
            "allocation": allocation,
            "timestamp": datetime.now().isoformat()
        })
        
        logger.info(f"[WARIA] ✅ Allocation complete: {allocation}")
        
        return allocation
    
    def _decide_allocation(self, tool: Dict) -> Dict[str, Any]:
        """Decide where tool should be allocated"""
        # Logic based on tool characteristics
        requestor = tool.get("requestor", "unknown")
        tool_type = tool.get("type", "unknown")
        
        allocation = {
            "primary_target": requestor,  # Return to requestor by default
            "clone_to": [],
            "make_global": False
        }
        
        # If tool is highly reusable, clone to multiple agents
        if tool_type == "alias" and "automation" in tool.get("purpose", "").lower():
            allocation["clone_to"] = ["D1_Puckfairy", "C1_Bash", "C2_Gunash"]
            allocation["make_global"] = True
        
        return allocation
    
    def _execute_allocation(self, tool: Dict, allocation: Dict):
        """Execute the allocation decision"""
        logger.info(f"[WARIA] 🎯 Allocating {tool['id']} to {allocation['primary_target']}")
        
        # Send to primary target
        # Send clones if needed
        if allocation["clone_to"]:
            logger.info(f"[WARIA] 📋 Cloning to: {', '.join(allocation['clone_to'])}")
        
        if allocation["make_global"]:
            logger.info(f"[WARIA] 🌍 Making tool global")


# Factory function to create the complete feedback loop system
def create_feedback_system() -> Dict[str, Any]:
    """
    Initialize complete feedback loop system with all agents.
    """
    bash_forge = BashToolForge()
    puckfairy_detector = PuckfairyAutomationDetector(bash_forge)
    diplo_analyzer = DiploLogAnalyzer(bash_forge)
    waria_allocator = WariaAllocationEngine()
    
    return {
        "bash": bash_forge,
        "puckfairy": puckfairy_detector,
        "diplo": diplo_analyzer,
        "waria": waria_allocator
    }


if __name__ == "__main__":
    # Test the feedback loop
    system = create_feedback_system()
    
    # Simulate Puckfairy detecting repeated command
    system["puckfairy"].track_command("git status")
    system["puckfairy"].track_command("git status")
    system["puckfairy"].track_command("git status")  # Triggers automation
    
    # Simulate Diplo analyzing logs
    mock_logs = {
        "localhost": ["EXECUTED: docker ps", "EXECUTED: docker ps", "EXECUTED: docker ps"],
        "narnia_vps": ["EXECUTED: systemctl status", "EXECUTED: systemctl status"]
    }
    system["diplo"].analyze_logs(mock_logs)
    
    # Simulate Gunash task request
    gunash_result = system["bash"].handle_gunash_task_request("Build and deploy agent system")
    
    print("\n=== Feedback Loop Test Complete ===")
    print(f"Pending tool requests: {len(system['bash'].pending_requests)}")
    print(f"Created tools: {len(system['bash'].created_tools)}")
